server:
  port: ${SPRING_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    open-in-view: false
    hibernate:

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.MySQLDialect

app:
  frontend:
    base-url: https://chcse.knu.ac.kr/auth

logging:
  level:
    kr.ac.knu.cse: DEBUG
    org:
      springframework:
        security: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
